language: python
cache: pip
python:
  - "2.6"
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_content_proxy_testing
  - KOTTI_TEST_DB_STRING=mysql+oursql://root@localhost:3306/kotti_content_proxy_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - travis_retry pip install "pip==1.3.1"  # fix issue with fanstatic==1.0a
  - travis_retry pip install "setuptools>=17.1"  # fix issue with mock==1.3.0
  - travis_retry pip install -e . -r requirements.txt --use-mirrors
  - travis_retry pip install psycopg2 oursql python-coveralls codecov
  - python setup.py dev
before_script:
  - psql -c 'create database kotti_content_proxy_testing;' -U postgres
  - mysql -e 'create database kotti_content_proxy_testing;'
script: py.test --tb=native --cov=kotti_content_proxy --cov-report=term-missing
after_success:
  - coveralls
  - codecov
